package com.citclops.cameralibrary;

public class CameraConstants {
	
	// Possibles valors White Balance
	public enum WHITE_BALANCE{AUTO, CLOUDY_DAYLIGHT, DAYLIGHT, FLUORESCENT, INCANDESCENT, SHADE, TWILIGHT, WARM_FLUORESCENT, UNKNOWN};
	
	// Possibles valors del Flash
	public enum FLASH_MODE{AUTO, OFF, ON, RED_EYE, TORCH};
	
	// Possibles valors del Color Effect
	public enum COLOR_EFFECT{NONE, MONO, NEGATIVE, SOLARIZE, SEPIA, POSTERIZE, WHITEBOARD, BLACKBOARD, AQUA, UNKNOWN};
	
	//Possibles valors del Antibanding
	public enum ANTIBANDING{AUTO, OFF, FIFTY, SIXTY, UNKNOWN};
	
	//Possibles valors del Scene
	public enum SCENE{MODE_ACTION, MODE_AUTO, MODE_BARCODE, MODE_BEACH, MODE_CANDLELIGHT, MODE_FIREWORKS, 
		MODE_LANDSCAPE, MODE_NIGHT, MODE_NIGHT_PORTRAIT, MODE_PARTY, MODE_PORTRAIT, MODE_SNOW, MODE_SPORTS, MODE_STEADYPHOTO,
		MODE_SUNSET, MODE_THEATRE, UNKNOWN};
		
	// Possible formats d'imatge
	public enum IMAGEFORMAT{JPEG, NV16, NV21, RGB_565, UNKNOWN, YUY2, YV12};
				
	public enum FOCUS_MODE{FOCUS_AUTO, FOCUS_CONTINUOUS_PICTURE, FOCUS_CONTINUOUS_VID, FOCUS_EDOF, FOCUS_FIXED,
		FOCUS_INFINITY, FOCUS_MACRO, UNKNOWN};	
}

